GET http://localhost:3001/api/notes/

###
DELETE http://localhost:3001/api/notes/66e3b45fc7f5214f6b5522c9

###
POST http://localhost:3001/api/notes 
content-type:application/json

{
  "content":"This is a test note",
  "important":true
}

###
POST http://localhost:3001/api/notes 
content-type:application/json

{
  "content":"Long text here",
  "important":true,
  "userId":"66f21da3c1630812450c76d4"
}

###
POST http://localhost:3001/api/notes 
content-type:application/json

{
  "content":"Another text here",
  "important":true,
  "userId":"66f21da3c1630812450c76d4"
}

###
PUT http://localhost:3001/api/notes/66e3b45fc7f5214f6b5522c9 

content-type:application/json

{
  "content":"This is a test note",
  "important":true
}

###
POST http://localhost:3001/api/users 
content-type:application/json

{
  "username":"Test",
  "name":"Test",
  "password":"Test"
}

###
POST http://localhost:3001/api/login
content-type:application/json

{
  "username":"Test",
  "password":"Test"
}

###
POST http://localhost:3001/api/notes 
content-type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3QiLCJpZCI6IjY2ZjIxZGEzYzE2MzA4MTI0NTBjNzZkNCIsImlhdCI6MTcyNzIyMzExNn0.o6EeGpF74Ps4Mf8BILBelQnT_AEVBZaOvkbB_7jHob4

{
  "content":"Another text here auth",
  "important":true
}